version: '3'

services:
  backend:
    container_name: backend-server-tp5
    restart: always
    build: .
    ports:
      - "4000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongodbtp5
    image: mongo
    ports:
      - "27018:27017"
    logging:
      driver: none